[project]
name = "or-boardgaming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gpiozero>=2.0.1",
    "opencv-python>=4.13.0.92",
    "pigpio>=1.78",
    "pyserial>=3.5",
    "rpi-gpio>=0.7.1",
    "rpi-lgpio>=0.6",
]
