
X_MOTOR_PINS = [24, 12]
Y_MOTOR_PINS = [25, 13]
Z_MOTOR_PINS = []

CLAW_SERVO_PIN = None

X_MOTOR_ENABLE_PIN = 5
Y_MOTOR_ENABLE_PIN = 6
Z_MOTOR_ENABLE_PIN = None

X_ENCODER_PINS = [14, 15]
Y_ENCODER_PINS = [7, 8]
Z_ENCODER_PINS = [1, 18]

X_FORWARD_LIMIT_SWITCH_PIN = 16
X_BACKWARD_LIMIT_SWITCH_PIN = 26
Y_FORWARD_LIMIT_SWITCH_PIN = 19
Y_BACKWARD_LIMIT_SWITCH_PIN = 20
TURN_INDICATOR_BUTTON_PIN = 21

# X_FWD_LIM = None
# X_BKD_LIM = None
# Y_FWD_LIM = None
# Y_BKD_LIM = None

REST_LOCATION = [0, 0] # placeholder
PIECE_STORAGE_LOCATION = [0, 0] # placeholder
MOTOR_SPEED = 0.4

COMMAND_FREQUENCY = 20 # 20 hz so 0.05 s

APPROX_GANTRY_DIMS_IN_CM =  50 # 100 # 19.5 in

BOARD_SQUARE_SIZE = 6 # irl size of total board in inches