

X_MOTOR_PINS = [25, 13]
Y_MOTOR_PINS = [24, 12]
GEARBOX_CPR = 700
IN_PER_LEAD_REV = .315 # how many inch per rev of lead screw
STEPS_PER_INCH = GEARBOX_CPR / IN_PER_LEAD_REV
Z_MOTOR_PINS = []

CLAW_SERVO_PIN = 18 
Z_SERVO_PIN = 23
Z_SERVO_MIN = 1/1000
Z_SERVO_MAX = 2.5/1000

X_MOTOR_ENABLE_PIN = 5
Y_MOTOR_ENABLE_PIN = 6

X_ENCODER_PINS = [7, 8]
Y_ENCODER_PINS = [14, 15]
Z_ENCODER_PINS = [1, 18]

Y_LIMIT_SWITCH_NEG_PIN = 26 # see physical board, marked as S3
Y_LIMIT_SWITCH_POS_PIN = 19 # marked as S4
Y_LIMIT_SWITCH_PIN = [20, 26]
TURN_INDICATOR_BUTTON_PIN = 21



REST_LOCATION = [0, 0] # placeholder
PIECE_STORAGE_LOCATION = [0, 0] # placeholder
MOTOR_SPEED = 0.8

COMMAND_FREQUENCY = 20 # 20 hz so 0.05 s