
X_MOTOR_PINS = [24, 12]
Y_MOTOR_PINS = [25, 13]
Z_MOTOR_PINS = []

CLAW_SERVO_PIN = None
Z_SERVO_PIN = 17 

X_MOTOR_ENABLE_PIN = 5
Y_MOTOR_ENABLE_PIN = 6
Z_MOTOR_ENABLE_PIN = None

X_ENCODER_PINS = [14, 15]
Y_ENCODER_PINS = [7, 8]
Z_ENCODER_PINS = [1, 18]

X_LIMIT_SWITCH_PIN = [16, 19]
Y_LIMIT_SWITCH_PIN = [20, 26]
TURN_INDICATOR_BUTTON_PIN = 21



REST_LOCATION = [0, 0] # placeholder
PIECE_STORAGE_LOCATION = [0, 0] # placeholder
MOTOR_SPEED = 0.8

COMMAND_FREQUENCY = 20 # 20 hz so 0.05 s